version: '3.8'

services:
  backend:
    build: ./backend
    container_name: studentools-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - backend_generated_papers:/app/generated_papers
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    
  studytoolsai-next:
    build: ./studytoolsai-next
    container_name: studentools-next
    ports:
      - "3000:3000"
    volumes:
      - ./studytoolsai-next:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - backend

volumes:
  backend_generated_papers: 